// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerifyEidAndCountyResidence.Data;

#nullable disable

namespace VerifyEidAndCountyResidence.Migrations
{
    [DbContext(typeof(VerifyEidCountyResidenceMattrContext))]
    partial class VerifyEidCountyResidenceMattrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VerifyEidAndCountyResidence.Data.Did", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DidData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DidId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DidTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dids");
                });

            modelBuilder.Entity("VerifyEidAndCountyResidence.Data.EidCountyResidenceDataPresentationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DidCountyResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DidEid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MattrPresentationTemplateReponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EidAndCountyResidenceDataPresentationTemplates");
                });

            modelBuilder.Entity("VerifyEidAndCountyResidence.Data.EidCountyResidenceDataPresentationVerify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Challenge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Did")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DidCountyResidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DidEid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvokePresentationResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignAndEncodePresentationRequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EidAndCountyResidenceDataPresentationVerifications");
                });

            modelBuilder.Entity("VerifyEidAndCountyResidence.Data.VerifiedEidAndCountyResidenceData", b =>
                {
                    b.Property<string>("ChallengeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLocality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("ChallengeId");

                    b.ToTable("VerifiedEidAndCountyResidenceData");
                });
#pragma warning restore 612, 618
        }
    }
}
